### ISSUE TITLE
prebuilt binaries for windows

### ISSUE THREAD

**Issue by mfazekas** [crypto-rb/rbnacl-libsodium#9]
We'd plan to use rbnacl in [next version](https://rubygems.org/gems/net-ssh/versions/4.0.0.alpha3) of net-ssh, to support some of the new features of openssh like ed25519 keys.

Since the user base of tools using of net-ssh is so big (capistrano, chef), i expect that compiling libsodium from source will be an issue on the windows platform. I've just tried to run windows-based ci, and they were failing the build:
https://ci.appveyor.com/project/mfazekas/net-ssh/build/job/9tcu1ye38e77416f

Would you consider precompiling windows binaries? For [bcrypt_pbkdf-ruby ](https://github.com/net-ssh/bcrypt_pbkdf-ruby) i'm using [rake compiler dock](https://github.com/net-ssh/bcrypt_pbkdf-ruby/blob/master/Rakefile) to cross build the binaries. Is this something you'd consider doing?

**Comment by tarcieri** [comment]
I'd consider it, however I don't have a Windows machine or any time to work on it, so it'd have to be more of a "PRs accepted" sort of thing.

**Comment by tisba** [comment]
Sorry for highjacking this... I noticed significantly increased build times of my projects and I noticed that it takes about 2 minutes to build rbnacl-libsodium-1.0.11 on my decent powered eight core box against Ruby 2.3.1. My question is: Are there any pre-build versions for any OS?

**Comment by tisba** [comment]
oh, okay, I thought this also provides some sort of binding. sorry for the noise and thanks for clearing this up!

**Comment by tarcieri** [comment]
FYI: I plan on deprecating this gem. Therefore I am closing all other open issues.

Please discuss any concerns on #29.
